export default function Terms() {
  return (
    <div className="pt-24 pb-16 max-w-3xl mx-auto px-4">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <div className="prose prose-invert text-gray-300 space-y-4 text-sm leading-relaxed">
        <p><strong>Last updated:</strong> March 2026</p>

        <h2 className="text-xl font-semibold text-white mt-6">1. Service Description</h2>
        <p>ReachRadar AI provides AI-powered social media algorithm auditing, content analysis, optimization tools, and daily post idea generation. Our service analyzes your social media data and generates actionable recommendations to improve your reach and engagement.</p>

        <h2 className="text-xl font-semibold text-white mt-6">2. Account Terms</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>You must provide accurate information when creating an account</li>
          <li>You are responsible for maintaining the security of your account</li>
          <li>You must be at least 13 years old to use this service</li>
        </ul>

        <h2 className="text-xl font-semibold text-white mt-6">3. Acceptable Use</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>You may only submit data that you have the right to analyze</li>
          <li>You may not use the service for spam or malicious purposes</li>
          <li>You may not attempt to reverse-engineer or exploit the service</li>
        </ul>

        <h2 className="text-xl font-semibold text-white mt-6">4. AI-Generated Content</h2>
        <p>Content generated by our AI, including audits, recommendations, scripts, captions, and daily idea plans, is provided as suggestions. You are responsible for reviewing and adapting any generated content before publishing it on your social media accounts. We do not guarantee specific results.</p>

        <h2 className="text-xl font-semibold text-white mt-6">5. Payments & Refunds</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>Free tier: 5 audits, 5 pre-post checks, and 1 daily idea per day</li>
          <li>Pro Monthly ($1.99/month): Unlimited audits, unlimited pre-post checks, and 3 daily ideas per day</li>
          <li>Pro Yearly ($9.99/year): Full Pro toolkit at the annual rate</li>
          <li>Refunds available within 7 days of purchase if unsatisfied</li>
        </ul>

        <h2 className="text-xl font-semibold text-white mt-6">6. Limitation of Liability</h2>
        <p>ReachRadar AI is provided "as is" without warranties. We are not responsible for any changes to your social media reach, engagement, or account status resulting from following our recommendations.</p>

        <h2 className="text-xl font-semibold text-white mt-6">7. Contact</h2>
        <p>Questions about these terms? Contact us at: <a href="mailto:gd@reachradarai.com" className="text-indigo-400 hover:underline">gd@reachradarai.com</a></p>
      </div>
    </div>
  );
}
