import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export async function generateAuditPDF(auditData) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const addPage = () => {
    const page = pdfDoc.addPage([612, 792]); // Letter size
    return page;
  };

  let page = addPage();
  let y = 740;

  const drawText = (text, options = {}) => {
    const {
      size = 11,
      bold = false,
      color = rgb(0.1, 0.1, 0.1),
      x = 50,
      maxWidth = 512,
    } = options;

    const usedFont = bold ? boldFont : font;

    // Simple word wrapping
    const words = text.split(' ');
    let line = '';
    const lines = [];

    for (const word of words) {
      const testLine = line ? `${line} ${word}` : word;
      const width = usedFont.widthOfTextAtSize(testLine, size);
      if (width > maxWidth && line) {
        lines.push(line);
        line = word;
      } else {
        line = testLine;
      }
    }
    if (line) lines.push(line);

    for (const l of lines) {
      if (y < 60) {
        page = addPage();
        y = 740;
      }
      page.drawText(l, { x, y, size, font: usedFont, color });
      y -= size + 4;
    }
    y -= 4;
  };

  // Header
  const riskColor =
    auditData.risk_score > 70
      ? rgb(0.9, 0.1, 0.1)
      : auditData.risk_score > 40
        ? rgb(0.9, 0.6, 0.0)
        : rgb(0.1, 0.7, 0.2);

  drawText('ReachRadar AI — Algorithm Audit Report', { size: 22, bold: true });
  y -= 8;
  drawText(`Platform: ${auditData.platform || 'Multi-platform'}`, { size: 13 });
  drawText(`Generated: ${new Date().toLocaleDateString()}`, { size: 10, color: rgb(0.5, 0.5, 0.5) });
  y -= 12;

  // Risk Score
  drawText(`RISK SCORE: ${auditData.risk_score}/100 (${auditData.risk_level})`, {
    size: 18,
    bold: true,
    color: riskColor,
  });
  y -= 4;

  drawText(`Predicted 30-Day Reach Drop: ${auditData.predicted_30day_reach_drop}`, { size: 13, bold: true });
  drawText(`Potential Monthly Loss: ${auditData.potential_monthly_loss}`, { size: 13, bold: true });
  y -= 8;

  // Summary
  if (auditData.summary) {
    drawText('EXECUTIVE SUMMARY', { size: 14, bold: true, color: rgb(0.2, 0.2, 0.6) });
    drawText(auditData.summary);
    y -= 8;
  }

  // Red Flags
  drawText('TOP RED FLAGS', { size: 14, bold: true, color: rgb(0.8, 0.1, 0.1) });
  if (auditData.top_red_flags) {
    for (const flag of auditData.top_red_flags) {
      const flagText = typeof flag === 'string' ? flag : `[${flag.severity?.toUpperCase()}] ${flag.flag}`;
      drawText(`• ${flagText}`, { size: 11 });
      if (flag.explanation) {
        drawText(`  ${flag.explanation}`, { size: 10, color: rgb(0.4, 0.4, 0.4) });
      }
    }
  }
  y -= 8;

  // Fix Plan
  drawText('6-STEP FIX PLAN', { size: 14, bold: true, color: rgb(0.1, 0.5, 0.2) });
  if (auditData.fix_plan) {
    for (const step of auditData.fix_plan) {
      const stepText =
        typeof step === 'string'
          ? step
          : `Step ${step.step}: ${step.action} (${step.timeline})`;
      drawText(stepText, { size: 11, bold: true });
      if (step.impact) {
        drawText(`  Impact: ${step.impact}`, { size: 10, color: rgb(0.3, 0.3, 0.3) });
      }
    }
  }
  y -= 8;

  // Positive Signals
  if (auditData.positive_signals?.length) {
    drawText('POSITIVE SIGNALS', { size: 14, bold: true, color: rgb(0.1, 0.6, 0.3) });
    for (const signal of auditData.positive_signals) {
      drawText(`✓ ${signal}`, { size: 11 });
    }
  }

  // Footer
  y = 30;
  page.drawText('Generated by ReachRadar AI — reachradar.ai', {
    x: 50,
    y,
    size: 9,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  return await pdfDoc.save();
}
